# --- Main Colors ---
background            #151311
foreground            #e8e1dd
cursor                #e8e1dd
cursor_text_color     #151311

selection_background  #51443b
selection_foreground  #f3dfd1

url_color             #e3c0a5

# --- ANSI Colors ---
color0                #151311
color1                #ffb4ab
color2                #e3c0a5
color3                #d6c3b6
color4                #dcc1ae
color5                #e3c0a5
color6                #d6c3b6
color7                #e8e1dd

color8                #4a4644
color9                #93000a
color10               #5a422e
color11               #51443b
color12               #564334
color13               #51443b
color14               #5a422e
color15               #ccc5c2

# --- Starship Prompt Bubbles ---
color255              #564334
color254              #dcc1ae
color253              #51443b
color252              #d6c3b6
color251              #5a422e
color250              #e3c0a5
color249              #93000a
color248              #ffb4ab

color232              #faddc9
color233              #3e2d1f
color234              #f3dfd1
color235              #3a2e25
color236              #ffdcc2
color237              #412c19
color238              #ffdad6
color239              #690005
color240              #faddc9

# Matched with unthemed light/dark
color243              #dcc1ae
color244              #ffb4ab
color245              #4a4644

# --- UI Elements ---
active_tab_foreground   #3e2d1f
active_tab_background   #dcc1ae
inactive_tab_foreground #faddc9
inactive_tab_background #564334

active_border_color     #dcc1ae
inactive_border_color   #95908d

# --- Marks ---
mark1_foreground        #27180c
mark1_background        #faddc9
mark2_foreground        #241a12
mark2_background        #f3dfd1
mark3_foreground        #2a1707
mark3_background        #ffdcc2
