# --- Main Colors ---
background            #1a1111
foreground            #f1dedd
cursor                #f1dedd
cursor_text_color     #1a1111

selection_background  #5d3f3d
selection_foreground  #ffdad7

url_color             #e2c28c

# --- ANSI Colors ---
color0                #1a1111
color1                #ffb4ab
color2                #e2c28c
color3                #e7bdb9
color4                #ffb3ae
color5                #e2c28c
color6                #e7bdb9
color7                #f1dedd

color8                #534342
color9                #93000a
color10               #594319
color11               #5d3f3d
color12               #733331
color13               #5d3f3d
color14               #594319
color15               #d8c2c0

# --- Starship Prompt Bubbles ---
color255              #733331
color254              #ffb3ae
color253              #5d3f3d
color252              #e7bdb9
color251              #594319
color250              #e2c28c
color249              #93000a
color248              #ffb4ab

color232              #ffdad7
color233              #571d1c
color234              #ffdad7
color235              #442928
color236              #ffdea7
color237              #402d04
color238              #ffdad6
color239              #690005
color240              #ffdad7

# Matched with unthemed light/dark
color243              #ffb3ae
color244              #ffb4ab
color245              #534342

# --- UI Elements ---
active_tab_foreground   #571d1c
active_tab_background   #ffb3ae
inactive_tab_foreground #ffdad7
inactive_tab_background #733331

active_border_color     #ffb3ae
inactive_border_color   #a08c8b

# --- Marks ---
mark1_foreground        #3b0809
mark1_background        #ffdad7
mark2_foreground        #2c1514
mark2_background        #ffdad7
mark3_foreground        #271900
mark3_background        #ffdea7
