# --- Main Colors ---
background            #161312
foreground            #e9e1e0
cursor                #e9e1e0
cursor_text_color     #161312

selection_background  #534342
selection_foreground  #f5dddb

url_color             #e7bdb9

# --- ANSI Colors ---
color0                #161312
color1                #ffb4ab
color2                #e7bdb9
color3                #d8c2c0
color4                #dfbfbd
color5                #e7bdb9
color6                #d8c2c0
color7                #e9e1e0

color8                #4a4645
color9                #93000a
color10               #5d3f3d
color11               #534342
color12               #584140
color13               #534342
color14               #5d3f3d
color15               #ccc5c4

# --- Starship Prompt Bubbles ---
color255              #584140
color254              #dfbfbd
color253              #534342
color252              #d8c2c0
color251              #5d3f3d
color250              #e7bdb9
color249              #93000a
color248              #ffb4ab

color232              #fcdbd8
color233              #402b2a
color234              #f5dddb
color235              #3b2d2c
color236              #ffdad7
color237              #442928
color238              #ffdad6
color239              #690005
color240              #fcdbd8

# Matched with unthemed light/dark
color243              #dfbfbd
color244              #ffb4ab
color245              #4a4645

# --- UI Elements ---
active_tab_foreground   #402b2a
active_tab_background   #dfbfbd
inactive_tab_foreground #fcdbd8
inactive_tab_background #584140

active_border_color     #dfbfbd
inactive_border_color   #968f8e

# --- Marks ---
mark1_foreground        #291716
mark1_background        #fcdbd8
mark2_foreground        #251918
mark2_background        #f5dddb
mark3_foreground        #2c1514
mark3_background        #ffdad7
