[config]
import_json_files = ["./extra_colors.json"]

[config.wallpaper]
set = true
command = "awww img --transition-type center {{ image }}"

[templates.gtk3]
input_path= '~/.config/matugen/templates/gtk/colors3.css'
output_path= '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path= '~/.config/matugen/templates/gtk/colors4.css'
output_path= '~/.config/gtk-4.0/colors.css'
post_hook= '~/.config/matugen/templates/gtk/setup.sh'

[templates.kde_colors_dark]
input_path= '~/.config/matugen/templates/kde/MaterialDark.colors'
output_path = '~/.local/share/color-schemes/MaterialDark.colors'

[templates.kde_colors_light]
input_path= '~/.config/matugen/templates/kde/MaterialLight.colors'
output_path = '~/.local/share/color-schemes/MaterialLight.colors'

[templates.kdeglobals_dark]
input_path= '~/.config/matugen/templates/kde/kdeglobals-dark'
output_path = '~/.config/matugen/templates/kde/output/kdeglobals-dark'

[templates.kdeglobals_light]
input_path= '~/.config/matugen/templates/kde/kdeglobals-light'
output_path = '~/.config/matugen/templates/kde/output/kdeglobals-light'
post_hook= '~/.config/matugen/templates/kde/setup.sh &' 

[templates.terminal]
input_path = '~/.config/matugen/templates/kitty/colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -USR1 kitty'

[templates.hypr]
input_path = '~/.config/matugen/templates/hypr/colors.lua'
output_path = '~/.config/hypr/config/colors.lua'
post_hook = 'hyprctl reload'
