[config]
source_color_index = 0
import_json_files = ["./extra_colors.json"]

[config.wallpaper]
set = true
command = "awww img --transition-type center {{ image }}"

[templates.gtk3]
input_path= '~/.config/matugen/templates/gtk/colors3.css'
output_path= '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path= '~/.config/matugen/templates/gtk/colors4.css'
output_path= '~/.config/gtk-4.0/colors.css'
post_hook= '~/.config/matugen/templates/gtk/setup.sh {{ mode }}'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty/colors.conf'
output_path = '~/.config/kitty/themes/Material.conf'
post_hook = "kitty +kitten themes --reload-in=all Material"

[templates.hypr]
input_path = '~/.config/matugen/templates/hypr/colors.lua'
output_path = '~/.config/hypr/config/colors.lua'

[templates.qt_color_scheme_dark]
input_path= '~/.config/matugen/templates/kde/dark/MaterialDark.colors'
output_path = '~/.local/share/color-schemes/MaterialDark.colors'

[templates.qt_color_scheme_light]
input_path= '~/.config/matugen/templates/kde/light/MaterialLight.colors'
output_path = '~/.local/share/color-schemes/MaterialLight.colors'

[templates.kdeglobals_light]
input_path= '~/.config/matugen/templates/kde/light/kdeglobals-light'
output_path = '~/.config/matugen/outputs/kde/kdeglobals-light'

[templates.kdeglobals_dark]
input_path= '~/.config/matugen/templates/kde/dark/kdeglobals-dark'
output_path = '~/.config/matugen/outputs/kde/kdeglobals-dark'
post_hook = '~/.config/matugen/templates/kde/setup.sh {{ mode }}'
